# Generated by Django 3.2 on 2021-04-24 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(max_length=200, upload_to='uploads/products/'),
        ),
    ]
